# Generated by Django 2.2.16 on 2021-04-07 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Model', '0007_auto_20210125_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgramingLanguage', models.PositiveIntegerField(null=True)),
                ('DataBase', models.PositiveIntegerField(null=True)),
                ('DataStructure', models.PositiveIntegerField(null=True)),
                ('FileProcessing', models.PositiveIntegerField(null=True)),
                ('ObjectOriented', models.PositiveIntegerField(null=True)),
                ('userPrograming', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LinerAlgebra', models.PositiveIntegerField(null=True)),
                ('Discrete_Math', models.PositiveIntegerField(null=True)),
                ('DifferentialEquation', models.PositiveIntegerField(null=True)),
                ('AdvancedMathematics', models.PositiveIntegerField(null=True)),
                ('Stochastic', models.PositiveIntegerField(null=True)),
                ('Statistics', models.PositiveIntegerField(null=True)),
                ('Calculus', models.PositiveIntegerField(null=True)),
                ('Operations_Researsh', models.PositiveIntegerField(null=True)),
                ('userMath', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InformationTheory', models.PositiveIntegerField(null=True)),
                ('Multimedia', models.PositiveIntegerField(null=True)),
                ('Intro_to_IS', models.PositiveIntegerField(null=True)),
                ('Intro_to_CS', models.PositiveIntegerField(null=True)),
                ('SystemAnalysis_And_Design', models.PositiveIntegerField(null=True)),
                ('userAcademic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
