# Generated by Django 3.2 on 2021-04-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0008_academic_math_programing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='math',
            name='userMath',
        ),
        migrations.RemoveField(
            model_name='programing',
            name='userPrograming',
        ),
        migrations.DeleteModel(
            name='Academic',
        ),
        migrations.DeleteModel(
            name='Math',
        ),
        migrations.DeleteModel(
            name='Programing',
        ),
    ]
