# Generated by Django 3.2 on 2021-04-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0009_auto_20210414_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
