# Generated by Django 3.2 on 2021-04-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0013_auto_20210419_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='id',
            new_name='Id',
        ),
    ]
