# Generated by Django 3.2 on 2021-04-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0014_rename_id_answer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
