# Generated by Django 3.2 on 2021-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0016_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bady', models.CharField(max_length=1000, null=True)),
                ('Correct_Answer', models.CharField(max_length=20, null=True)),
                ('User_Answer', models.CharField(max_length=20, null=True)),
                ('Status', models.CharField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
