# Generated by Django 3.2 on 2021-04-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0019_rename_questions_qqqqq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QQQQQ',
        ),
    ]
