# Generated by Django 3.2 on 2021-04-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0020_delete_qqqqq'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQQQQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Bady', models.CharField(max_length=1000, null=True)),
                ('Correct_Answer', models.CharField(max_length=20, null=True)),
                ('User_Answer', models.CharField(max_length=20, null=True)),
                ('Status', models.CharField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=200, null=True)),
            ],
        ),
    ]
