# Generated by Django 3.2 on 2021-04-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0023_auto_20210419_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqqqq',
            name='Status',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qqqqq',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
