# Generated by Django 3.2 on 2021-04-20 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0025_auto_20210419_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='Status',
            new_name='kind',
        ),
    ]
