# Generated by Django 3.2 on 2021-04-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0029_auto_20210421_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
